name = "unlighthouse-dev"
account_id = "5904138d55ca25d5670dca6adf99894e"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat_v2" ]
main = ".output/server/index.mjs"
assets = { directory = ".output/public", binding = "ASSETS" }

[[kv_namespaces]]
binding = "KV"
id = "29fb5bd433c44a989ac1fbd72940f1e4"

[[kv_namespaces]]
binding = "CACHE"
id = "8f765d0c531c41edb94790f2d31d8dba"

[[d1_databases]]
binding = "DB"
database_name = "unlighthouse"
database_id = "5274d98a-9e23-4a78-b9af-46444ec20b2a"

[[analytics_engine_datasets]]
binding = "TOOL_ANALYTICS"
dataset = "unlighthouse_tool_usage"
